### PR TITLE
Feature simple visualizer

### LINKED ISSUE #27: #27 Simple visualizer
- [x] Plugin should be able to generate html representation of given graph structure
- [x] Plugin should be able to make difference in representation of directed and undirected graph

### PR DESCRIPTION
**Pull request by borismarkovsv73**
Implementation of simple visualizer. Added as a new module and connected to build and run scripts.

### CODE REVIEW

**Review by teodord25 — DISMISSED** [review]
lgtm

**Review by darkokos — APPROVED** [review]
LGTM

**Review by teodord25 — APPROVED** [review]
aint no way :skull:

**Review by aleksaaaa02 — APPROVED** [review]
Good 👍

**Pull request merged**
