### PR TITLE
Fix build scripts

### PR DESCRIPTION
**Pull request by teodord25**
https://github.com/darkokos/sok-project/pull/21#issuecomment-1925112083

image

### CODE REVIEW

**Review by drag0dev — APPROVED** [review]
Linux :+1:

**Review by darkokos — CHANGES_REQUESTED** [review]
The venv file tree differs between operating systems. This way, the script always fails on Windows. Also, the venv directory does not necessarily have to be called venv, so you will double the virtual environment of users that already have a virtual environment set up.

**Comment by teodord25** [comment]
I demonstrated that the previous version fails on Linux?
How and why are you even running Bash on Windows?

**Comment by teodord25** [comment]
Well, I can't even set Docker up because pywin32 relies on Windows' kernel.
I love Windows.
I guess I just won't be running it then.
Godspeed

**Pull request closed without merging**
