### PR TITLE
Fix/bird view

### PR DESCRIPTION
**Pull request by teodord25**
kids these days just break your shit and tell you to fix it

### CODE REVIEW

**Review by drag0dev — DISMISSED** [review]
birb

**Comment by teodord25** [comment]
> birb

the best language

https://github.com/TodePond/DreamBerd

**Review by darkokos — APPROVED** [review]
LGTM

**Review by aleksaaaa02 — APPROVED** [review]
Good, watch on naming convetions. 👍

**Comment by teodord25** [comment]
it's not about conventions

**Comment by teodord25** [comment]
it's about sending a message

**Pull request merged**
